# Generated by Django 4.1.5 on 2023-02-07 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '__first__'),
        ('restaurant', '0002_order_quantities'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='outlet',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='outlet', to='customer.outlet'),
            preserve_default=False,
        ),
    ]
