# Generated by Django 4.1.5 on 2023-02-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('customerID', models.TextField()),
                ('ready', models.BooleanField(default=False)),
                ('items', models.ManyToManyField(related_name='item', to='customer.item')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
